=== David646464/dam2_repositorio/BASES/proyectos/documentos/Actores1.dtd
<?xml version='1.0' encoding='UTF-8'?>
<!--- El elmento actores contiene cero o más actores. -->
<!ELEMENT Actores (Actor)*>
<!--- El elemento Actor debe tener nome, sexo y fecha de nacimiento. -->
<!ELEMENT Actor (Nome,Sexo,DataNacemento)>
<!---  Actor debe tener obligatorio el atributo id -->
<!ATTLIST Actor
    id ID #REQUIRED
 >
<!--- (#PCDATA) – contenido textual, un conjunto de caracteres -->
<!ELEMENT Nome (#PCDATA)>
<!ELEMENT Sexo (#PCDATA)>
<!ELEMENT DataNacemento (#PCDATA)>
<!--- #IMPLIED: permite no especificar el atributo (es opcional).-->
<!ATTLIST DataNacemento
    formato CDATA #IMPLIED
  >

=== David646464/dam2_repositorio/BASES/documentos/Actores1.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Actores SYSTEM "Actores1.dtd">
<Actores>
    <Actor id="A59">
        <Nome>Eliabeth Shue</Nome>
        <Sexo>muller</Sexo>
        <DataNacemento formato="dd/mm/aaaa"> 06/10/1963</DataNacemento>             
    </Actor>
    <Actor id="A139">
        <Nome>Jhonny Depp</Nome>
        <Sexo>home</Sexo>
        <DataNacemento formato="dd/mm/aaaa">09/06/1963</DataNacemento>       
    </Actor>
    <Actor id="A100">
        <Nome>Harrison Ford</Nome>
        <Sexo>home</Sexo>
        <DataNacemento formato="dd/mm/aaaa">13/07/1943</DataNacemento>       
    </Actor>    
        <Actor id="A120">
        <Nome>Demi Moore</Nome>
        <Sexo>muller</Sexo>
        <DataNacemento formato="dd/mm/aaaa">13/10/1966</DataNacemento>       
    </Actor>    
        <Actor id="A40">
        <Nome>Diane Keaton</Nome>
        <Sexo>muller</Sexo>
        <DataNacemento formato="dd/mm/aaaa">15/01/1952</DataNacemento>       
    </Actor>    
</Actores>
